# custom app config
# overrides DCAPE/apps/drone/dcape-app/docker-compose.yml

version: '2'

services:
  app:
    ports:
      - 8080:8080
    labels:
      - "traefik.http.services.app-${APP_TAG}.loadbalancer.server.port=8080"
    environment:
      - JOURNALIST_DEBUG=true
      - JOURNALIST_ADMIN_USERNAME=${USER_NAME}
      - JOURNALIST_ADMIN_PASSWORD=${USER_PASS}
      - JOURNALIST_DATABASE_TYPE=postgres
      - JOURNALIST_DATABASE_CONNECTION=postgres://${PGUSER}:${PGPASSWORD}@db/${PGDATABASE}?sslmode=disable
      - JOURNALIST_SERVER_BINDIP=0.0.0.0
      - JOURNALIST_SERVER_PORT=8080
      - JOURNALIST_SERVER_ENDPOINT_API=${HTTP_PROTO}://${APP_SITE}/api
      - JOURNALIST_SERVER_ENDPOINT_WEB=${HTTP_PROTO}://${APP_SITE}/web
